-- AlterTable
ALTER TABLE "facility" ADD COLUMN     "ecriCapAtStreet" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "ecriMaxStepCents" INTEGER NOT NULL DEFAULT 3000,
ADD COLUMN     "ecriMinGapCents" INTEGER NOT NULL DEFAULT 1500,
ADD COLUMN     "ecriMinMonthsSinceChange" INTEGER NOT NULL DEFAULT 9,
ADD COLUMN     "ecriMinStepCents" INTEGER NOT NULL DEFAULT 500,
ADD COLUMN     "ecriPercentBasisPoints" INTEGER NOT NULL DEFAULT 1000;
